@echo off
echo Killing old Python processes on port 8000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8000') do taskkill /F /PID %%a 2>nul
timeout /t 2 /nobreak >nul
echo Starting backend server...
python app.py
